[package]
name = "entity-component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytifex-utils = { git = "https://github.com/bytifex/bytifex-utils.git" }
