[package]
name = "game_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
log = "0.4"
tokio = { version = "1.20", features = ["full"] }
vek = "0.15"
parking_lot = "*"
muleengine = { path = "muleengine" }
sdl2_opengl_muleengine = { path = "sdl2_opengl_muleengine" }

[workspace]
members = [
	"muleengine",
	"sdl2_opengl_muleengine"
]

# muleengine
# vek = "0.15"
# image = "0.24"
# assimp = "0.3.1"
# assimp-sys = "0.3.1"
# tempfile = "3"
# parking_lot = "*"
